
services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    depends_on:
      - db

  db:
    image: alpine
    container_name: sqlite_db
    volumes:
      - ./estoque.db:/app/estoque.db
    command: tail -f /dev/null 

volumes:
  pg_data:
